services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5200
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5200:5200"
    volumes:
      - ./Backend/app.db:/app/app.db
    environment:
      - Igdb__ClientSecret=${IGDB_CLIENT_SECRET}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}